# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(default=datetime.datetime(2016, 12, 23, 5, 30, 55, 200630))),
            ],
        ),
    ]
